[package]
name = "rust-tcp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.1.0"
etherparse = "0.13.0"
nix = "0.26.2"
tun-tap =  { version = "0.1.3", features = ["libc"]}
